#!/usr/bin/env bash
# Creates a file containing its pid, displays text indefinitely, displays different text when receiving SIGTERM and SIGINT signals, and  deletes the file and terminates itself when receiving SIGQOUIT or SIGTERM
echo $$ >> /var/run/my_script.pid
trap "echo I hate the kill command; rm /var/run/my_script.pid; exit 0" SIGTERM
trap "echo Y U no love me; exit 0" SIGINT
trap "echo Y U no love me; rm /var/run/my_script.pid; exit 0" SIGQUIT
while true
do
	echo "To infinity and beyond"
	sleep 2
done

