#!/usr/bin/env bash
# This script displays 1 to 100 in a list format, Fizz for multiples of 3, Buzz for multiples of 5 and FizzBuz for multiples of 3 and 5
COUNT=1
until [ $COUNT -gt 100 ]
do
	if [ $((COUNT % 3)) == 0 ] && [ $((COUNT % 5)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((COUNT % 3)) == 0 ]
	then
		echo "Fizz"
	elif [ $((COUNT % 5)) == 0 ]
	then
		echo "Buzz"
	else
		echo "$COUNT"
	fi
	((COUNT++))
done

