#!/usr/bin/env bash
# This script displays 1 to 20 with text for the 4th, 9th and 17th iteration
i=1
while [ $i -le 20 ]; do
	echo $i
	if [ $i -eq 4 ]; then
		echo "bad luck from China"
	elif [ $i -eq 9 ]; then
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]; then
		echo "bad luck from Italy"
	fi
	((i++))
done
