#!/usr/bin/env bash
# This script displays the current directory contents in a list format where only the part of the name after the first dash is displayed
for FILE in *
do
	echo "$FILE" | cut -d '-' -f 2-
done

